### ISSUE TITLE
Slot attention initialization params no gradients

### ISSUE THREAD

**Issue by davidetalon** [addtt/object-centric-library#3]
Hi Andrea, thank you for the interesting work!
I've notice that in slot attention initialization parameters self.slots_mu and self.slots_log_sigma are learnable. Though, [sampling](https://github.com/addtt/object-centric-library/blob/78b69ab936b836787c34bd7acdb692fe05e8baa1/models/slot_attention/model.py#L166) from the associated gaussian distribution is not based on the reparameterization trick. Hence, no gradients are propagated to them.

Is it intended?

**Comment by addtt** [comment]
Hi Davide, you are totally right and we should in principle backprop through sampling. I think this shouldn't matter in practice in our case. In general, however, you might want to learn distinct mus and sigmas for each slot (see ablations in the Slot Attention paper). In that case of course this is crucial. Thanks for spotting this!
